name: 'actions-sns-tag-alert'
description: 'Sends a notification to SNS when a new tag is created'
inputs:
  aws_key_id:
    description: "AWS Access Key ID"
    required: true
  aws_secret_key:
    description: "AWS Secret Access Key"
    required: true
  topic_arn:
    description: "The SNS topic to publish to"
    required: true
  tag_pattern:
    description: "A regex pattern to match valid tag names; defaults to all tags"
    required: false
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - -i ${{ inputs.aws_key_id }}
    - -k ${{ inputs.aws_secret_key }}
    - -t ${{ inputs.topic_arn }}
    - -p ${{ inputs.tag_pattern }}
